version: '3.8'

services:
  app:
    build:
      context: .
      args:
        GEMINI_API_KEY: AIzaSyB2Ny-uqnwANVOXAXS3cT-U1AZ3bvldKAU
    ports:
      - "5810:4173"
    environment:
      - GEMINI_API_KEY=AIzaSyB2Ny-uqnwANVOXAXS3cT-U1AZ3bvldKAU